backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "intro"
  label: "Introduction"
  files:
    - name: "intro"
      label: "Texte d’introduction"
      file: "intro_resources.json"
      fields:
        - label: "Texte (FR)"
          name: "text"
          widget: object
          fields:
            - label: "Français"
              name: "fr"
              widget: text


  - name: "faq"
  label: "FAQ"
  files:
    - name: "faq"
      label: "Questions / Réponses"
      file: "faq.json"
      fields:
        - label: "Questions"
          name: "items"
          widget: list
          fields:
            - label: "Question"
              name: "question"
              widget: string
            - label: "Réponse"
              name: "answer"
              widget: text
